//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 03:23:07 afternoon CST 
//

package testdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.sun.istack.internal.NotNull;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RowidObject" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OrganizationID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".{1,14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SalesCoverageSegment">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".{1,14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BusinessAreaGroup">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".{1,14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SalesCoverageSegmentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".{1,20}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RecordStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[NY]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * @author a-kun.xiang@hp.com
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "MDCPOrgID", "businessAreaGroup", "salesCoverageSegment", "effectiveDate", "expirationDate", "active" })
@XmlRootElement(name = "OrganizationSalesCoverageSegmentAssignment")
public class TestData04 {

	@XmlElement(name = "MDCP_Org_ID", required = true)
	protected String MDCPOrgID;
	@XmlElement(name = "Business_Area_Group", required = true)
	protected String businessAreaGroup;
	@XmlElement(name = "Sales_Coverage_Segment", required = true)
	protected String salesCoverageSegment;
	@XmlElement(name = "SCS_Effective_Start_Date", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar effectiveDate;
	@XmlElement(name = "SCS_Effective_End_Date")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar expirationDate;
	@XmlElement(name = "Active", required = true)
	protected String active;

	/**
	 * Gets the value of the salesCoverageSegment property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSalesCoverageSegment() {
		return salesCoverageSegment;
	}

	/**
	 * Sets the value of the salesCoverageSegment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSalesCoverageSegment(String value) {
		this.salesCoverageSegment = value;
	}

	/**
	 * Gets the value of the businessAreaGroup property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getBusinessAreaGroup() {
		return businessAreaGroup;
	}

	/**
	 * Sets the value of the businessAreaGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setBusinessAreaGroup(String value) {
		this.businessAreaGroup = value;
	}

	/**
	 * @return the mDCPOrgID
	 */
	public String getMDCPOrgID() {
		return MDCPOrgID;
	}

	/**
	 * @param mDCPOrgID
	 *            the mDCPOrgID to set
	 */
	public void setMDCPOrgID(String mDCPOrgID) {
		MDCPOrgID = mDCPOrgID;
	}

	/**
	 * @return the effectiveDate
	 */
	public XMLGregorianCalendar getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * @param effectiveDate
	 *            the effectiveDate to set
	 */
	public void setEffectiveDate(XMLGregorianCalendar effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * @return the expirationDate
	 */
	public XMLGregorianCalendar getExpirationDate() {
		return expirationDate;
	}

	/**
	 * @param expirationDate
	 *            the expirationDate to set
	 */
	public void setExpirationDate(XMLGregorianCalendar expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * @return the active
	 */
	public String getActive() {
		return active;
	}

	/**
	 * @param active
	 *            the active to set
	 */
	public void setActive(String active) {
		this.active = active;
	}
}
